// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OctApp.Data;

#nullable disable

namespace OctApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231019163805_umper_01")]
    partial class umper_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OctApp.Models.AppEnvironment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppEnvironments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7400),
                            IsDeleted = false,
                            Name = "Live",
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7430),
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7440),
                            IsDeleted = false,
                            Name = "Test",
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7440),
                            Value = 2
                        });
                });

            modelBuilder.Entity("OctApp.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankCode = "044",
                            BankId = "044",
                            BankName = "Access Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7490),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7490)
                        },
                        new
                        {
                            Id = 2,
                            BankCode = "023",
                            BankId = "023",
                            BankName = "Citibank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7500),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7500)
                        },
                        new
                        {
                            Id = 3,
                            BankCode = "063",
                            BankId = "063",
                            BankName = "Diamond Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7500),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7500)
                        },
                        new
                        {
                            Id = 4,
                            BankCode = "0",
                            BankId = "0",
                            BankName = "Dynamic Standard Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7510),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7510)
                        },
                        new
                        {
                            Id = 5,
                            BankCode = "050",
                            BankId = "050",
                            BankName = "Ecobank Nigeria",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7510),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7510)
                        },
                        new
                        {
                            Id = 6,
                            BankCode = "070",
                            BankId = "070",
                            BankName = "Fidelity Bank Nigeria",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7510),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7520)
                        },
                        new
                        {
                            Id = 7,
                            BankCode = "011",
                            BankId = "011",
                            BankName = "First Bank of Nigeria",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7520),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7520)
                        },
                        new
                        {
                            Id = 8,
                            BankCode = "214",
                            BankId = "214",
                            BankName = "First City Monument Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7520),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7520)
                        },
                        new
                        {
                            Id = 9,
                            BankCode = "058",
                            BankId = "058",
                            BankName = "Guaranty Trust Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7530),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7530)
                        },
                        new
                        {
                            Id = 10,
                            BankCode = "030",
                            BankId = "030",
                            BankName = "Heritage Bank Plc",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7530),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7530)
                        },
                        new
                        {
                            Id = 11,
                            BankCode = "301",
                            BankId = "301",
                            BankName = "Jaiz Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7530),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7530)
                        },
                        new
                        {
                            Id = 12,
                            BankCode = "082",
                            BankId = "082",
                            BankName = "Keystone Bank Limited",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7540),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7540)
                        },
                        new
                        {
                            Id = 13,
                            BankCode = "101",
                            BankId = "101",
                            BankName = "Providus Bank Plc",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7540),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7540)
                        },
                        new
                        {
                            Id = 14,
                            BankCode = "076",
                            BankId = "076",
                            BankName = "Polaris Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7540),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7550)
                        },
                        new
                        {
                            Id = 15,
                            BankCode = "221",
                            BankId = "221",
                            BankName = "Stanbic IBTC Bank Nigeria Limited",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7550),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7550)
                        },
                        new
                        {
                            Id = 16,
                            BankCode = "068",
                            BankId = "068",
                            BankName = "Standard Chartered Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7550),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7550)
                        },
                        new
                        {
                            Id = 17,
                            BankCode = "232",
                            BankId = "232",
                            BankName = "Sterling Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7560),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7560)
                        },
                        new
                        {
                            Id = 18,
                            BankCode = "100",
                            BankId = "100",
                            BankName = "Suntrust Bank Nigeria Limited",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7560),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7560)
                        },
                        new
                        {
                            Id = 19,
                            BankCode = "032",
                            BankId = "032",
                            BankName = "Union Bank of Nigeria",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7560),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7560)
                        },
                        new
                        {
                            Id = 20,
                            BankCode = "033",
                            BankId = "033",
                            BankName = "United Bank for Africa",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7570),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7570)
                        },
                        new
                        {
                            Id = 21,
                            BankCode = "215",
                            BankId = "215",
                            BankName = "Unity Bank Plc",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7570),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7570)
                        },
                        new
                        {
                            Id = 22,
                            BankCode = "035",
                            BankId = "035",
                            BankName = "Wema Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7570),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7570)
                        },
                        new
                        {
                            Id = 23,
                            BankCode = "057",
                            BankId = "057",
                            BankName = "Zenith Bank",
                            CreatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7580),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2023, 10, 19, 17, 38, 5, 508, DateTimeKind.Local).AddTicks(7580)
                        });
                });

            modelBuilder.Entity("OctApp.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("OctApp.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("AppEnvironmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OctApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AppEnvironmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OctApp.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppEnvironmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("LiveBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("LivePrivateKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LivePublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TestBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TestPrivateKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestPublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("OctApp.Models.Token", b =>
                {
                    b.HasOne("OctApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OctApp.Models.Wallet", b =>
                {
                    b.HasOne("OctApp.Models.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OctApp.Models.User", b =>
                {
                    b.Navigation("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
